FROM golang:1.21 as BUILDER

WORKDIR /home
COPY . .
RUN go get github.com/akrylysov/algnhsa && \
    go get github.com/sirupsen/logrus && \
    go build ./main.go

FROM openeuler/openeuler:22.03
LABEL maintainer="Zhou Yi 1123678689@qq.com"
RUN useradd -s /bin/bash BigFiles
USER BigFiles
WORKDIR /home/BigFiles
COPY --chown=BigFiles:group --from=BUILDER /home/main /home/BigFiles/main

EXPOSE 5000
ENTRYPOINT ["/home/BigFiles/main"]