name: golangci-lint
on:
  pull_request:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

env:
  GOPRIVATE: "github.com/opensourceways"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4
      - name: config github
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER: ${{ secrets.USER_NAME }}
        run: echo "machine github.com login $USER password $TOKEN" > ~/.netrc
      - name: golangci-lint
        uses: golangci/golangci-lint-action@master
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: latest
          # Optional: golangci-lint command line arguments.
          #
          # Note: By default, the `.golangci.yml` file should be at the root of the repository.
          # The location of the configuration file can be changed by using `--config=`
          args: -v --config=.golangci.yml --max-same-issues=0

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        env:
          GITHUB_AUTHENTICATION_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          args: -exclude-dir api -exclude-dir tests ./...
      - name: Unit tests
        run: go test -race -count=1 -v ./...
      - name: cleanup
        run: rm -f ~/.netrc
